--- 
title: "NYPD Complaint Data Current"
author: "Jiayuan Cui, Yujie Zhou, Xuchen Wang"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

New York City, as the financial center of the United States, people from all walks of life populated here. Thus, to maintain a safe environment in the city is the most crucial task facing the government and institutions. In order to control the crimes, it should take as the priority to understand the distribution of crimes in NYC and identity the factors (i.e. times, location, gender, etc.) that would be associated with crime rate. 

In this project, our group have thoroughly analyzed the NYPD Complaint Data provided by New York City Police Department (NYPD). The objective is to help people identity and visualize crime occurrences in the New York City. We have used various exploratory data analysis methods to answer the questions below:

1. Which type of crimes occurred most frequently in New York in year 2021?
2. How does crime rate changes by day?
3. How does crime rate changes by day of week?
4. How does crime rate changes by time of day?
5. How do crime patterns in boroughs based on timings of the crimes, days of the crimes, and types of crimes?

Our final goal for this project is not only to help people living in New York City to identity and reduce the risk to encounter crimes, but also help NYPD and national institutions to deploy and allocate resources and capital in highly dangerous areas to control crimes. 